"""Versioned constants that define sampled-frame person detection evidence."""

DETECTOR_PROVIDER_NMS_IOU = 0.70
DETECTOR_MAX_DETECTIONS = 300
GENERIC_ULTRALYTICS_IMAGE_SIZE = 1280
GENERIC_ULTRALYTICS_CONFIDENCE = 0.035

PERSON_LOCAL_NMS_IOU = 0.48
MINIMUM_PERSON_FOOT_Y = 0.18
SHALLOW_PERSON_FOOT_Y = 0.34
SHALLOW_PERSON_CONFIDENCE = 0.12
SHALLOW_PERSON_GRASS_RATIO = 0.52
PERSON_FILTER_POLICY_VERSION = "pitch-person-v3"
APPEARANCE_FEATURE_SCHEMA_VERSION = "hsv-histogram-v1"

GENERIC_BALL_FILTER_POLICY_VERSION = "generic-coco-ball-v2"
GENERIC_BALL_MINIMUM_CENTER_Y_RATIO = 0.30
GENERIC_BALL_MAXIMUM_BOX_SIZE_PIXELS = 24.0
GENERIC_BALL_MINIMUM_GRASS_RATIO = 0.24
GENERIC_BALL_DEDUPLICATION_RADIUS_PIXELS = 10.0
